environment:
  test_profile: default
  matrix:
    - java_version: 1.6.0
    - java_version: 1.7.0
    - java_version: 1.8.0
      test_profile: short
platform: x64
install:
  - ps: .\ci\appveyor.ps1
build_script:
  - ps: |
      $env:JAVA_HOME="$($env:JAVA_8_HOME)"
      cmd /c mvn install -DskipTests=true -D"maven.javadoc.skip"=true -B -V 2>&1
test_script:
  - ps: |
      $env:JAVA_HOME="$($env:JAVA_PLATFORM_HOME)"
      cmd /c mvn -B -D"ccm.java.home"="$($env:JAVA_8_HOME)" -D"ccm.maxNumberOfNodes"=1 -D"cassandra.version"=$($env:cassandra_version) test -P $($env:test_profile) 2>&1
on_finish:
  - ps: .\ci\uploadtests.ps1
cache:
  - C:\Users\appveyor\.m2
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\deps -> .\ci\appveyor.ps1
